---
name: orienteer.ru
description: Спортивное ориентирование в Тюмени
meta_description: Клуб спортивного ориентирования 'Ермак'
markdown: kramdown
highlighter: pygments
logo: false
paginate: 2
baseurl: "/"
domain_name: http://new.orienteer.ru
google_analytics: UA-501594-1
gems:
- jekyll-paginate
- jekyll-admin
url: rss
author: Александр Ефимов
