name: orienteer.ru
description: Спортивное ориентирование в Тюмени
meta_description: "Клуб спортивного ориентирования 'Ермак'"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 3
baseurl: /
domain_name: 'http://new.orienteer.ru'
google_analytics: 'UA-501594-1'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'rss'
author:         'Александр Ефимов'
